name: Base

on: workflow_call

jobs:
  base:
    strategy:
      matrix:
        node-version: [20.x]

    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./

      - name: Install deps
        run: npm ci
